-- Enable AUTO_INCREMENT on ALL Tables
-- Run this in phpMyAdmin SQL tab

USE spartan_data;

-- System Tables
ALTER TABLE users MODIFY id INT AUTO_INCREMENT;
ALTER TABLE user_sessions MODIFY id INT AUTO_INCREMENT;
ALTER TABLE system_settings MODIFY id INT AUTO_INCREMENT;
ALTER TABLE activity_logs MODIFY id INT AUTO_INCREMENT;
ALTER TABLE dashboard_stats MODIFY id INT AUTO_INCREMENT;
ALTER TABLE table_assignments MODIFY id INT AUTO_INCREMENT;
ALTER TABLE data_submissions MODIFY id INT AUTO_INCREMENT;
ALTER TABLE drafts MODIFY id INT AUTO_INCREMENT;
ALTER TABLE report_submissions MODIFY id INT AUTO_INCREMENT;
ALTER TABLE report_submission_data MODIFY id INT AUTO_INCREMENT;

-- Report Tables
ALTER TABLE campuspopulation MODIFY id INT AUTO_INCREMENT;
ALTER TABLE admissiondata MODIFY id INT AUTO_INCREMENT;
ALTER TABLE enrollmentdata MODIFY id INT AUTO_INCREMENT;
ALTER TABLE graduatesdata MODIFY id INT AUTO_INCREMENT;
ALTER TABLE employee MODIFY id INT AUTO_INCREMENT;
ALTER TABLE leaveprivilege MODIFY id INT AUTO_INCREMENT;
ALTER TABLE libraryvisitor MODIFY id INT AUTO_INCREMENT;
ALTER TABLE pwd MODIFY id INT AUTO_INCREMENT;
ALTER TABLE waterconsumption MODIFY id INT AUTO_INCREMENT;
ALTER TABLE treatedwastewater MODIFY id INT AUTO_INCREMENT;
ALTER TABLE electricityconsumption MODIFY id INT AUTO_INCREMENT;
ALTER TABLE solidwaste MODIFY id INT AUTO_INCREMENT;
ALTER TABLE foodwaste MODIFY id INT AUTO_INCREMENT;
ALTER TABLE fuelconsumption MODIFY id INT AUTO_INCREMENT;
ALTER TABLE distancetraveled MODIFY id INT AUTO_INCREMENT;
ALTER TABLE budgetexpenditure MODIFY id INT AUTO_INCREMENT;
ALTER TABLE flightaccommodation MODIFY id INT AUTO_INCREMENT;

-- Verify (run this to check)
SELECT TABLE_NAME, EXTRA 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA='spartan_data' AND COLUMN_NAME='id' AND COLUMN_KEY='PRI';
